package.json, src/lib/screenshot-url.js, src/pages/index.js
=> build: add to query only necessary params

src/components/presets/index.js, src/components/presets/midudev.js, src/components/presets/news.js
=> build: add midudev template

src/components/presets/adobe.js, src/components/presets/article.js, src/components/presets/bytesandhumans.js, src/components/presets/chrisbiscardi.js, src/components/presets/fauna.js, src/components/presets/index.js, src/components/presets/midudev.js, src/components/presets/news.js, src/components/presets/rauchg.js, src/components/presets/simple.js, src/components/presets/swyxdotio.js, src/components/presets/thepracticaldev.js, src/components/presets/vercel.js
=> feat: add adobe & chrisbiscardi preset

packages/app/src/components/live-editor.js
=> build: hide live preview overflow

packages/app/src/components/presets/pedro.js
=> Fix pedro preset

packages/app/src/components/presets/contentz.js
=> Fix contentz preset

packages/app/package.json, packages/app/src/components/json-viewer.js, packages/app/src/pages/editor.js
=> Update json-viewer component

packages/app/src/components/presets/midudev.js
Simplify template and use new logo.
=> feat: midudev template - use new layout and logo

packages/app/src/components/presets/ajames.js, packages/app/src/components/presets/index.js
👋
Found you via: https://ped.ro/blog/generating-open-graph-images
I'd love to add this as a preset and use it on my [personal site](https://ajames.dev).
Let me know if you're happy with it
=> build: add ajames preset

packages/app/src/components/presets/ajames.js
👋
- Flattened query variables object
- Updated default image
- Slight visual update
=> build: flattened query variables on ajames preset

packages/app/src/components/presets/ajames.js
This took me far too long to work out what was going wrong 🤦
=> fix: added url decode to bg img on ajames preset

packages/app/src/components/presets/ajames.js
Last one, promise 😅
I couldn't get the dynamic images to pull in correctly (see https://github.com/microlinkhq/cards/issues/92)
I've updated the default image for now, which might require a regeneration of the card preview if you're feeling generous!
=> fix: ajames updated default img src position and mask

packages/app/src/components/presets/smhutch.js
Fixes the  design on Chrome/Safari.
=> fix: improve SMHutch preset on Chrome

packages/app/src/hooks/use-screenshot-url.js
=> fix: ensure preset query param is present

packages/app/src/components/presets/ckgrafico.js
=> Hotfix bg color in ckgrafico template

packages/app/src/components/presets/richhaines.js
Ive tried to fix the dimensions so that the crad plays nice with Twitter as a og card. I hope this works 😅
=> added dimensions to card

packages/app/src/components/presets/dracula.js
New preset build for https://draculatheme.com
=> build: add dracula preset

packages/app/src/components/presets/draculashop.js
=> feat: add draculashop preset

packages/app/src/components/live-editor.js, packages/app/src/components/mql.js, packages/app/src/components/presets/twitter.js, packages/app/src/hooks/index.js, packages/app/src/hooks/use-mounted-ref.js
Add use-mounted-ref inspired by:
https://www.debuggr.io/react-update-unmounted-component/
=> fix: prevent unnecessary re-renderings

CONTRIBUTING.md, packages/app/package.json, packages/app/scripts/consts.js, packages/app/scripts/create-preset.js, packages/app/scripts/generate-previews.js
=> chore: Add `CONTRIBUTING`

CONTRIBUTING.md
Hey there,
I found a typo on the `CONTRIBUTING.md` file while working on #284. This pull request fixes it.
=> Fix small typo @ CONTRIBUTING.md

packages/app/src/components/presets/workos.js
Some small fixes after testing with a wider range of images.
=> feat: allow different image ratios to WorkOS preset

packages/app/src/components/presets/workos-docs.js
Add a conditional around the category pill so that it won't display if the category is an empty string.
=> Add conditional around category pill

packages/app/src/components/presets/workos-docs.js
Add `font-display: block` and tweak alignment
=> Update WorkOS Docs template

packages/app/src/components/presets/workos-docs.js
Tweak gray color for better legibility
=> feat: improve WorkOS docs card
